# -*- coding: utf-8 -*-
"""IRIS_OASIS_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vJxrJSrrH19DTx3Qq_ppmx1uyEx72tvN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/drive/MyDrive/internship/Iris.csv")
data

data.describe()

data["Species"].unique()

data.groupby("Species").size()

corr_matrix = data.corr(numeric_only = True)

import seaborn as sns
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(10, 5))


sns.heatmap(corr_matrix, annot=True, cmap='Greens', ax=ax)


plt.show()

X = data.iloc[:, 1:5].values
y = data.iloc[:, 5].values

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

colors = ["red", "green", "blue"]


plt.figure()
sns.pairplot(data.drop("Id", axis=1), hue="Species", height=5, markers=["o", "s", "D"], palette=colors)

plt.show()

from sklearn.neighbors import KNeighborsClassifier as KNC
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

model = KNC(n_neighbors=3)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)*101
print('Accuracy: ' + str(round(accuracy, 2)) + '%')